apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
  labels:
    app: myflaskapp
spec:
  containers:
  - name: test-container
    image: psrv3/batch29cmapp:latest
    ports:
    - containerPort: 5001
    env:
    - name: NAME
      valueFrom:
        configMapKeyRef:
          name: my-flask-config
          key: NAME
    - name: DB_HOST
      valueFrom:
        configMapKeyRef:
          name: my-flask-config
          key: DB_HOST
    - name: DB_PORT
      valueFrom:
        configMapKeyRef:
          name: my-flask-config
          key: DB_PORT
