apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    name: myapp
  name: myapp
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      name: myapp
  template:
    metadata:
      labels:
        name: myapp
    spec:
      containers:
      - image: psrv3/gfgbatch38flaskapp:v1.0.0
        name: myapp
