apiVersion: v1
kind: Service
metadata:
  labels:
    name: myapp
  name: myappsvc
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: myapp
    # matchExpressions:
    # - key: name
    #   operator: In
    #   values:
    #   - myapp
    #   - myapplication
  type: NodePort
